name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Go to project folder and install
        run: cd antalya-miniapp && npm install
      - name: Build
        run: cd antalya-miniapp && npm run build
        env:
          VITE_BASE_PATH: /my-tele-bot/
      - name: Add .nojekyll
        run: cd antalya-miniapp && touch dist/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: antalya-miniapp/dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
